name: EAS Build
on:
  push:
    branches:
      - main
      - firebase-distribute

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_COGNITO_USER_POOL_ID=${{ secrets.EXPO_PUBLIC_COGNITO_USER_POOL_ID }}" > .env
          echo "EXPO_PUBLIC_COGNITO_CLIENT_ID=${{ secrets.EXPO_PUBLIC_COGNITO_CLIENT_ID }}" >> .env
          echo "EXPO_PUBLIC_AWS_ACCESS_KEY_ID=${{ secrets.EXPO_PUBLIC_AWS_ACCESS_KEY_ID }}" >> .env
          echo "EXPO_PUBLIC_AWS_SECRET_ACCESS_KEY=${{ secrets.EXPO_PUBLIC_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "EXPO_PUBLIC_API_URL=https://4mf6hjno08.execute-api.eu-west-1.amazonaws.com" >> .env

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        run: npx expo login --non-interactive

      - name: Build Android
        run: eas build --platform android --profile preview --non-interactive

      - name: Build iOS
        run: eas build --platform ios --profile preview --non-interactive

      - name: Get build URL
        run: |
          echo "Android build completed! Check the build at:"
          echo "https://expo.dev/accounts/orbasker/projects/Weightly-client/builds"
          echo "iOS build completed! Check the build at:"
          echo "https://expo.dev/accounts/orbasker/projects/Weightly-client/builds" 